config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  root to: 'home#index' 
  resources :events
  resources :postnews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :subject, {length: {maximum: 10}}
  validates :info, {presence: true, length: {maximum: 300}}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
      new_event_path
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :password])
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: :index

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: '新規作成が成功しました' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: '更新が成功しました' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: '削除が成功しました' }
      format.json { head :no_content }
    end
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :description, :start_date, :end_date)
    end

    def move_to_index
      if user_signed_in? == false || current_user.login_type == 2
        redirect_to  root_path
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    topic = Topic.all
    @topic = topic.where(flag: 1).order('created_at DESC')
    @topic_none = topic.where(flag: 2)
  end
end

app/controllers/postnews_controller.rb
class PostnewsController < ApplicationController

  # before_action :move_to_index, except: :index
  before_action :move_to_index

  def index
    topic = Topic.all
    @topic = topic.where(flag: 1).order('created_at DESC')
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.create(info: create_params[:info], subject: create_params[:subject], flag: 1)
    if @topic.save
      flash[:notice] = "送信しました"
      redirect_to(postnews_index_path)    
    else
      render(new_postnews_path)
    end
  end

  def show
    @topic = Topic.find_by(id: params[:id])
  end

  def edit
    @topic = Topic.find_by(id: params[:id])
  end

  def update
    topic = Topic.find_by(id: params[:id])
    if topic.update(create_params)
      flash[:notice] = "更新しました"
      redirect_to(postnews_index_path)
     else
      # redirect_to(postnews_index_path)
      redirect_to(edit_postnews_path(topic.id))
      flash[:notice] = "更新できませんでした。やりなおしてください"
    end
  end

  def destroy
    topic = Topic.find_by(id: params[:id])
    topic.destroy
    flash[:notice] = "削除しました"
    redirect_to(postnews_index_path)
  end

  private
  def create_params
    params.permit(:info, :subject)
  end

  def move_to_index
    if user_signed_in? == false || current_user.login_type == 2
      redirect_to  root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/postnews_helper.rb
module PostnewsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="cal_entry">
    <ul class="cal_entry--title">
      <li class="cal_entry--title__label"><%= form.label :内容, class: "field_title--label" %></li>
      <li class="cal_entry--title__val"><%= form.text_field :title, class: "field_title--input", placeholder: "6文字以内"%></li>
    </ul>

    <ul class="cal_entry--date">
      <li class="cal_entry--date__label"><%= form.label :対象日, class: "field_start--label" %></li>
      <li class="cal_entry--date__val"><%= form.date_field :start_date, class:"field_start--select" %></li>
    </ul>

    <div class="actions">
      <%= form.submit '送信', class: 'action_button' %>
    </div>

  </div>

<% end %>

app/views/events/edit.html.erb
<div class="wrap">
  <h1><i class="fas fa-calendar-alt"></i> 選択した日程の編集</h1>
  <%= render 'form', event: @event %>
</div>

  <div class="nav_three">
    <i class="fas fa-caret-right"></i>
    <%= link_to '編集リストへ戻る', events_path %> |
    <%= link_to 'トップ画面へ', root_path %>
  </div>
  

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="wrap-edit">
  <h1><i class="fas fa-calendar-alt"></i> 編集リスト</h1>
  <h2><i class="fas fa-edit"></i> 作成済リスト</h2>

  <table>
    <thead>
      <tr>
        <th class="th-date">日付</th>
        <th class="th-subj">内容</th>
        <th class="th-ope" colspan="2">操作</th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td class="td-date"><%= event.start_date.strftime('%Y/%m/%d') %></td>        
          <td class="td-subj"><%= event.title %></td>
          <td class="td-ope"><%= link_to '編集', edit_event_path(event) %></td>
          <td class="td-ope"><%= link_to '削除', event, method: :delete, data: { confirm: '削除してよろしいですか？' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>
<br>

<div class="nav_three">
  <i class="fas fa-caret-right"></i>
  <%= link_to '新規作成', new_event_path %> |
  <%= link_to 'トップ画面へ', root_path %>
</div>

app/views/events/new.html.erb
<div class="wrap">
  <h1><i class="fas fa-calendar-alt"></i>
  カレンダ新規作成</h1>
  <h2 class="disp-smart">
    <i class="fas fa-exclamation-circle"></i>
    スマートフォン使用時は3文字までしか表示されません
  </h2>
  <%= render 'form', event: @event %>
</div>

<div class="nav_three">
  <i class="fas fa-caret-right"></i>
  <%= link_to '編集画面へ', events_path, class: 'btn_back' %> |
  <%= link_to 'トップ画面へ', root_path %> | 
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
</div>

<p class="buttons">
  <i class="fas fa-caret-right"></i> 
  <%= link_to "新着メッセージ一覧管理へ", postnews_index_path %> 
</p>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="wrap">
<h1>確認画面</h1>

  <div class="cal_entry">
    <p class="cal_entry--date">
      <strong>日付:</strong>
      <%= @event.start_date.strftime('%Y/%m/%d') %>
    </p>

    <p class="cal_entry--title">
      <strong>内容:</strong>
      <%= @event.title %>
    </p>
  </div>
</div>

<div class="nav_three">
  <i class="fas fa-caret-right"></i>
  <%= link_to '編集画面へ戻る', edit_event_path(@event) %> |
  <%= link_to '編集リストへ戻る', events_path %> |
  <%= link_to 'トップ画面へ', root_path %>
</div>

app/views/home/index.html.erb
<html>
  <head>
    <title>東横線日吉美杏館縮毛矯正リペアストレートパーマ<</title>
  </head>
  <body>

    <header>
      <ul>
        <li class="login">ログイン</li>
        <li class="new">新規登録</li>
      </ul>
    </header>

    <div class="shop-name">
      <ruby>
        CUT<rt>カット</rt>
      </ruby>
      <ruby>
        HOUSE<rt>ハウス</rt>
      </ruby>
      <ruby>
        美杏館<rt>ビアンカン</rt>
      </ruby>   
    </div>

    <div class="grad">
      <ul class="slider">
        <li><%= image_tag 'entr.jpg' %></li>
        <li><%= image_tag 'in_01.jpg' %></li>
        <li><%= image_tag 'in_02.jpg' %></li>
        <li><%= image_tag 'entr_02.jpg' %></li>
      </ul>
    </div>

    <section class="whatNew">
      <div class="whatNew-header">
        <p class="whatNew-header__logo">
          <%= image_tag 'yuko_logo.jpg' %>
        </p>
        <p class="whatNew-header__subject">
          Information/お知らせ
        </p>
      </div>

      <% if @topic.present? %>
        <% @topic.each do |topic| %>
          <div class="whatNew-info">
            <p class="whatNew-info--date">
              <%= topic.created_at.to_s(:datetime_jp) %>
              <span><%= topic.subject%></span>
            </p>
            <p class="whatNew-info--content">
              <%= topic.info %>
            </p>
        <% end %>     
      <% else %>
        <% @topic_none.each do |topic| %>
          <div class="whatNew-info">
            <p class="whatNew-info--date">
              <span><%= topic.subject%></span>
            </p>
            <p class="whatNew-info--content">
              <%= topic.info %>
            </p>
        <% end %>       
      <% end %>

    </section>

    <section class="feature">
      <div class="feature-one">
        <p class="feature-one--logo"><%= image_tag 'yuko_logo.jpg' %></p>
              
        <h1>YUKOSYSTEM認定店</h1>
      </div>
      <div class="feature-two">
        「ユウコシステムリペア」は、「ユウコ」の名でNYですでにトップブランドとして知れ渡り、ハリウッドスターやファッションモデルが愛用。
        すでに雑誌やTVでも紹介されています。輝くようなストレートヘアは、いまNYでもブーム。くせ毛が多いとされる西洋人にとって、
        手間と費用を十分にかけて手に入れるストレートヘアはステイタスの証とも言えます。超高級サロンでのみ扱うユウコは、
        NYの女性のあこがれのブランドなのです。
        そんな技術を私たちは体験できています。縮毛矯正数多くあれど是非、お試しになってみてください。
        私たちはネットワークを通してリペアを追求する仲間たちと、よりよい技術のご提供ができるように勉強会を重ねています。
        お客様のニーズにあった新しい情報と技術を心がけています。<br><br>
        <i class="fas fa-caret-right"></i>
        <%= link_to 'Yukoシステムをもっと知る', 'http://www.yukoyamashita.com/jpn/about/index.html', {target: "_blank"} %>
      </div>
    </section>




    <section class="detail">
      <!--タブ-->
      <ul class="tab-group">
        <li class="tab is-active">営業日</li>
        <li class="tab">メニュー & 料金</li>
        <li class="tab">特典・クーポン</li>
        <li class="tab">アクセス</li>
        <li class="tab">店舗情報</li>
      </ul>

      <!--タブを切り替えて表示するコンテンツ-->
      <div class="panel-group">
        <div class="panel is-show">
          <div>
            <div class="reservation">
              <i class="fas fa-caret-right"></i>
            </div>
          <div id="calendar"></div>
          </div>
        </div>
 
        <div class="panel">
          <ul class="panel-item">
            <li>縮毛矯正リペア</li>
            <li>カラーリペア<span>(リペアしながらカラーができます)</span></li>
            <li>クリニックパーマ</li>
            <li>デジタルパーマ</li>  
            <li>アルカリカラー</li>
            <li>香草カラー</li>              
            <li>マニュキュア</li> 
            <li>カット</li> 
            <li>シャンプー</li>
            <li>トリートメント</li>
            <li>ヘッドエステ<span>(マッサージし・シャンプー・ドライ)</span></li>
            <li>クリームバス</li>
          </ul>

          <ul class="panel-val">
            <li>5,200 - 26,500円</li>
            <li><span>リペア料金 + </span>3,000 - 5,000円</li>
            <li>5,200 - 10,500円</li>                
            <li>12,000円</li>
            <li>4,200 - 6,500円</li>
            <li>3,200 - 6,500円</li>
            <li>5,000円</li>
            <li>3,300 - 4,000円</li>
            <li>700 - 1,000円</li>
            <li>2,000 - 5,000円</li>
            <li>2,500円</li>
            <li>3,500円</li>
          </ul>
        </div>

        <div class="panel">
          <div class="panel-qupon others">
            <p>初めてのご来店でのリペア施術 <span>2,000円 割引</span></p>
            <p>初めてのご来店でリペア以外の施術 <span>10% OFF</span></p>
            <p>お誕生日月 <span>20% OFF</span></p>
            <p class="other"><span>その他の特典</span><br>
            ・クーポン券で割引<br>
            ・貯まったポイントで割引<br></span>
            ・毎年１月２月の年始は１０％割引
            </p>
          </div>         
        </div>

        <div class="panel">
          <div style='width: 800px;'>
            <div class="panel-areaone">
              <p class="panel-areaone--address">
                <i class="fas fa-map-marker-alt"></i>
                <span class="lineone">所在地</span><br>
                〒223-0061<br>
                横浜市港北区日吉2-15-3<br>
                Tel: 045-563-3804<br>
                フリーダイヤル: 0120-122-180<br><br>
                <span class="byWalk"><i class="fas fa-walking"></i> 電車でお越しのお客様</span>
                <span class="byline">日吉駅より徒歩6分</span>
                <span class="byCar"><i class="fas fa-car"></i> お車でお越しのお客様</span>
                <span class="byline">三井のリパーク日吉２丁目第３駐車場ご利用で駐車券発行致します。</span>
              </p>

              <div id="map">
                <%= render partial: 'layouts/ggmap' %>
              </div>
            </div>

            <p class="maplink">
              <%= link_to 'Google Mapはこちら', 'https://www.google.com/maps/dir/%E7%A5%9E%E5%A5%88%E5%B7%9D%E7%9C%8C%E6%A8%AA%E6%B5%9C%E5%B8%82%E6%B8%AF%E5%8C%97%E5%8C%BA%E6%97%A5%E5%90%89%EF%BC%92%E4%B8%81%E7%9B%AE%EF%BC%91+%E6%97%A5%E5%90%89%E9%A7%85/%E3%80%92223-0061+%E7%A5%9E%E5%A5%88%E5%B7%9D%E7%9C%8C%E6%A8%AA%E6%B5%9C%E5%B8%82%E6%B8%AF%E5%8C%97%E5%8C%BA%E6%97%A5%E5%90%89%EF%BC%92%E4%B8%81%E7%9B%AE%EF%BC%91%EF%BC%95%E2%88%92%EF%BC%93/@35.5553578,139.6453084,17z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x60185f76e18c9d4d:0xc4a6f4b87d35fcb0!2m2!1d139.6468632!2d35.5532868!1m5!1m1!1s0x60185f79ae19db49:0x11c9fe4752ef56d5!2m2!1d139.6473594!2d35.5574144!3e2?hl=ja', {class: "ggllink", target: "_blank"} %>
            </p>

          </div>
        </div>

        <div class="panel">

          <div class="onlySp">
            <p class="sbj">定休日</p>
            <p class="line">毎週火曜日・第二水曜日・第三日曜日</p>
            <p class="sbj">最終受付</p>
            <p class="line">(リペア)pm5:00(その他のメニュー)pm6:00
                (要予約)日曜・祭日1時間早くなります</p>
            <p class="sbj"><i class="fas fa-map-marker-alt"></i> 所在地</p>
            <p class="val">〒223-0061<br>横浜市港北区日吉2-15-3</p>
            <p class="sbj"><i class="far fa-envelope"></i> eメール</p>
            <p class="val">biankan@cute.email.ne.jp</p>
            <p class="sbj"><i class="fas fa-phone"></i> フリーダイヤル</p>
            <p class="val">0120-122-180</p>
            <p class="sbj"><i class="fas fa-fax"></i> 電話番号</p>
            <p class="val">045-563-3804</p>

          </div>

          <ul class="panel-item general-left">
            <li class="panel-item--left">定休日</li>
            <li class="panel-item--left">最終受付</li>
            <li class="panel-item--left">所在地</li> 
            <li class="panel-item--left">eメール</li>    
            <li class="panel-item--left">フリーダイヤル</li>
            <li class="panel-item--left">電話番号</li>    
          </ul>

          <ul class="panel-val general-right">
            <li class="panel-val--right">毎週火曜日・第二水曜日・第三日曜日</li>
            <li class="panel-val--right twoline">(リペア)pm5:00(その他のメニュー)pm6:00<br>
                (要予約)日曜・祭日1時間早くなります</li>
            <li class="panel-val--right twoline">〒223-0061<br>横浜市港北区日吉2-15-3</li> 
            <li class="panel-val--right">biankan@cute.email.ne.jp</li>    
            <li class="panel-val--right">0120-122-180</li>
            <li class="panel-val--right">045-563-3804</li>   
          </ul>        
        </div>
      </div>
    </section>

    <footer>
      <h4> COPYRIGHT(C)</h4>
      <p>美杏館</p>
      <h4>ALL RIGHTS RESERVED.</h4>
    </footer>

  <div class="admin_tool">
    <% if user_signed_in? %>
      <p class="admin"><%= link_to 'カレンダ管理', new_event_path %></p>
      <p class="admin_two"><%= link_to '新着管理', postnews_index_path %>
      <p class="logout"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>
    <% end %>
  </div>

  </body>
</html>

app/views/layouts/_ggmap.html.erb
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, 
                  internal: {id: 'map'}}, 
                  function(){markers = handler.addMarkers([
                  {
                    "lat": 35.557414,
                    "lng": 139.647359,
                    "infowindow": "美杏館"
                  }
                ]);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                handler.getMap().setZoom(16);
                });
</script>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BianKan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content="縮毛矯正,ユウコシステム,リペア">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//maps.google.com/maps/api/js?key=<%= ENV['GGLMAP_KEY'] %>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/postnews/create.html.erb
<%= flash[:notice] %>
送信しました

app/views/postnews/edit.html.erb
<p class="flash"><%= flash[:notice] %></p>

<div class="newswrap">

  <h1>新着メッセージ編集</h1>
  <p class="note"><span>*</span> は必須入力項目</p>
  <%= form_tag("/postnews/#{@topic.id}", method: "patch") do%>

    <ul class="form-one">
      <li class="form-one__title"><%= label_tag :タイトル %></li>
      <li class="form-one__form"><%= text_field_tag :subject, "#{@topic.subject}" %></li>
    </ul>

    <ul class="form-one sec">
      <li class="form-one__title">
        <span>*</span><%= label_tag :内容 %>
        <br><p>300字以内</p>
      </li>
      <li class="form-one__form"><%= text_area_tag :info, "#{@topic.info}" %></li>
    </ul>

    <%= submit_tag "更新", class: "updbtn" %>
  <% end %>
  <br>
  <p class="buttons">
    <%= link_to "一覧に戻る", postnews_index_path %> | 
    <%= link_to "トップページへ戻る", root_path %>
  </p>
</div>

app/views/postnews/index.html.erb
<p class="flash"><%= flash[:notice] %></p>

<div class="newswrap">

  <h1>新着メッセージ一覧管理</h1>

  <p class="newbtn"><%= link_to('新規登録', new_postnews_path) %></p>

  <ul class="headerline">
    <li class="headerline-date">日付</li>
    <li class="headerline-title">タイトル</li>
    <li class="headerline-content">内容</li>
    <li class="headerline-btn1"></li>
    <li class="headerline-btn2"></li>    
  </ul>

  <% @topic.each do |topic| %>
    <ul class="contentline">
      <li class="contentline-date"><%= topic.created_at.to_s(:datetime_jp) %></li>
      <li class="contentline-title"><%= topic.subject %></li>
      <li class="contentline-content"><%= topic.info %></li>
      <li class="contentline-btn">
        <p><%= link_to("編集", edit_postnews_path(topic.id)) %></p>
      </li>
      <li class="contentline-btn">
        <p><%= link_to("削除", "/postnews/#{topic.id}", method: "delete", data: {confirm: "削除しますか？"} ) %></p>
      </li>    
    </ul>
  <% end %>

  <br>
  <p class="buttons">
    <i class="fas fa-caret-right"></i> 
    <%= link_to "トップページへ戻る", root_path %><br>
    <i class="fas fa-caret-right"></i>
    <%= link_to "カレンダ新規作成へ", new_event_path %>
  </p>

</div>

app/views/postnews/new.html.erb
<div class="newswrap">

  <h1>新規メッセージ作成</h1>
  <p class="note"><span>*</span> は必須入力項目</p>

  <%= form_tag("/postnews") do %>

    <% @topic.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>

    <ul class="form-one">
      <li class="form-one__title"><%= label_tag :タイトル %></li>
      <li class="form-one__form"><%= text_field_tag :subject, "#{@topic.subject}" %></li>
    </ul>

    <ul class="form-one sec">
      <li class="form-one__title">
        <span>*</span><%= label_tag :内容 %>
        <br><p>300字以内</p>
      </li>
      <li class="form-one__form"><%= text_area_tag :info, "#{@topic.info}" %></li>
    </ul>

    <%= submit_tag "投稿", class: "updbtn" %>
  <% end %>
  <br>
  <p class="buttons">
    <%= link_to "一覧に戻る", postnews_index_path %> | 
    <%= link_to "トップページへ戻る", root_path %>
  </p>
</div>

app/views/postnews/update.html.erb
てすと